
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Tidal_Island_development

test:
  <<: *default
  database: Tidal_Island_test

production:
  <<: *default
  database: Tidal_Island_production
  username: Tidal_Island
  password: <%= ENV['TIDAL_ISLAND_DATABASE_PASSWORD'] %>
